version: "3"

networks:
  my-network:
    driver: bridge

#VOLUMES
volumes:
  dir-site:
    driver_opts:
      type: "nfs"
      device: /home/tuannq/Documents/quocTuan02/php/mycode/sites
      o: bind
  database_data:

services:
  # container PHP
  my-php:
    container_name: php-product
    build:
      dockerfile: Dockerfile
      context: ./php/
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/

  # container HTTPD
  my-httpd:
    container_name: c-httpd01
    image: "httpd:latest"
    hostname: httpd
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "9999:80"
      - "443:443"
  # container MYSQL
  database:
    image: mysql:8.0
    ports:
      - "8021:3306"
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: tuannq
      MYSQL_PASSWORD: demo
      MYSQL_ROOT_HOST: '%'


